### ISSUE TITLE
Couple questions or maybe it is a bug

### ISSUE THREAD

**Issue by victor-vexargames** [ue4plugins/HoverPlugin#1]
Just checking this out. I re compiled for 4.17.1 the steps were to drop the plugin directory into a projects plugin folder it gave me a few warnings and I recompiled the plugin for 4.17.1, then started using it.

Testing with the a simple sphere (my project happens to be using a 2d Camera Capture to render an overview map which attached to the UMG) The sphere appears to have a red square around it in the Camera Capture image, I have tried changing the sphere to use the different choices offered in the plugin all show this red square around the sphere. Also please note when I tried different components like Async or Blueprint I get a small red square under the sphere with a tiny red vector line attached to it which looks like a debug mode but I haven't turned it on or can see a way to disable it.

If you want any images to support this bug let me know I can generate them or what I figure is more then likely is that I did something wrong like trying to use the plugin with 4.17.1. 

Another thing that would make it more designer friendly is to have some blueprint samples showing how to control or attach the hover forces to the player so you can build a playable hovering player or what ever.

Thank you for the cool plugin!

-Vex

I figured out what was causing the red box it was a line trace from an AI I had running but it was odd it was hitting it across the level.

**Comment by gmpreussner** [comment]
Glad you figured it out. I'm not planning to implement any sample projects for this plug-in due to lack of time, sorry!
